language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
sudo: false
env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1
install: travis_retry composer install --prefer-source --no-interaction
script: composer test
